name: petbox
version: 0.1.0.0
description: "Javran's ProjectEuler Toolbox."
maintainer: Javran Cheng <javran.c@gmail.com>
github: Javran/petbox

ghc-options: -Wall -O2

dependencies:
  - base
  - mtl
  - containers
  - arithmoi

library:
  exposed-modules: Petbox
  source-dirs: src

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - QuickCheck
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
